version: '3.2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
    networks:
      apinet:
        aliases:
          - zookeeper
  kafka:
    image: 127.0.0.1:5000/savior-kafka
    build:
      context: "./control/logging"
      dockerfile: Dockerfile
    ports:
      - target: 9555
        published: 9555
        protocol: tcp
        mode: host
    environment:
      CFSSL_SHARED_SECRET: "de1069ab43f7f385d9a31b76af27e7620e9aa2ad5dccd264367422a452aba67f"
      HOSTNAME_COMMAND: "docker info | grep ^Name: | cut -d' ' -f 2"      
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:SSL,OUTSIDE:SSL
      KAFKA_ADVERTISED_PROTOCOL_NAME: OUTSIDE
      KAFKA_ADVERTISED_PORT: 9555
      KAFKA_PROTOCOL_NAME: INSIDE
      KAFKA_PORT: 9455
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      apinet:
        aliases:
          - kafka
  cfssl:
    image: 127.0.0.1:5000/savior-cfssl
    build: "./control/savior-ca"
    ports:
      - "3030:3030"
    networks:
      apinet:
        aliases:
          - cfssl
  api:
    image: 127.0.0.1:5000/savior-api
    build: "./control/api_server"
    ports:
      - "17141:17141"
      - "17504:17504"
    environment:
      CFSSL_SHARED_SECRET: "de1069ab43f7f385d9a31b76af27e7620e9aa2ad5dccd264367422a452aba67f"
      SWARM_HOST: ${hostname -f}
    depends_on:
      - kafka
      - cfssl
      - api_server_postgres
    networks:
      apinet:
        aliases:
          - api
  dropper_callback:
    image: 127.0.0.1:5000/savior-dropper_callback
    build: "./external/dropper_callback"
    ports:
      - "8080:8080"
    # hostname: dropper1
    # domainname: evil.io
    networks:
      apinet:
        aliases:
          - dropper_callback
  target_1:
    image: 127.0.0.1:5000/savior-target_1
    build: "./targets/demo-target"
    depends_on:
      - kafka
      - api
    stdin_open: true
    tty: true
    networks:
      apinet:
        aliases:
          - target_1
  api_server_postgres:
    image: postgres:9.3
    volumes:
      - db-data:/var/lib/postgresql/data/pgdata
    environment:
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_USER: "postgres"
      PGDATA: "/var/lib/postgresql/data/pgdata"
      POSTGRES_DB: "api_server_postgres"
    deploy:
      placement:
        constraints: [node.role == manager]
    networks:
      apinet:
        aliases:
          - api_server_postgres
          - postgres
volumes:
  db-data:
networks:
  apinet:
    external: true