version: '3.2'
services:
  registry:
    restart: always
    image: registry:2
    ports:
      - 5000:5000
    networks:
      apinet:
        aliases:
          - registry
networks:
  apinet:
    external: true