version: '2'
services:
  kafka:
    build: "./control/logging"
    ports:
      - "2181:2181"
      - "9092:9092"
    environment:
      ADVERTISED_HOST: kafka
      ADVERTISED_PORT: "9092"
      CFSSL_SHARED_SECRET: "de1069ab43f7f385d9a31b76af27e7620e9aa2ad5dccd264367422a452aba67f"
  cfssl:
    build: "./control/savior-ca"
    ports:
      - "3030:3030"
  api:
    build: "./control/api_server"
    ports:
      - "17141:17141"
      - "17504:17504"
    environment:
      CFSSL_SHARED_SECRET: "de1069ab43f7f385d9a31b76af27e7620e9aa2ad5dccd264367422a452aba67f"
    depends_on:
      - kafka
      - cfssl
    links:
      - "kafka:kafka"
      - "cfssl:cfssl"
  sensor_1:
    build: "./sensors/dummy"
    ports:
      - "11000:11000"
      - "5002:5002"
    depends_on:
      - kafka
      - api
    command: python lsof_sensor.py --public-key-path ./cert/rsa_key.pub --private-key-path ./cert/rsa_key --api-host api --sensor-port 11000 --sensor-hostname sensor_1
  sensor_2:
    build: "./sensors/dummy"
    ports:
      - "11001:11001"
    depends_on:
      - kafka
      - api
    command: python lsof_sensor.py --public-key-path ./cert/rsa_key.pub --private-key-path ./cert/rsa_key --api-host api --sensor-port 11001 --sensor-hostname sensor_2
  dropper_callback:
    build: "./external/dropper_callback"
    ports:
      - "8080:8080"
    # hostname: dropper1
    # domainname: evil.io
  target_1:
    build: "./targets/base"
    depends_on:
      - kafka
      - api
    stdin_open: true
    tty: true
