version: '3.2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
    networks:
      apinet:
        aliases:
          - zookeeper
  kafka:
    image: localhost:5000/savior-kafka
    build:
      context: "./control/logging"
      dockerfile: Dockerfile
    ports:
      - target: 9555
        published: 9555
        protocol: tcp
        mode: ingress
    environment:
      CFSSL_SHARED_SECRET: "de1069ab43f7f385d9a31b76af27e7620e9aa2ad5dccd264367422a452aba67f"
      KAFKA_ADVERTISED_HOST_NAME: "sensing-kafka.savior.internal"      
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9455,OUTSIDE://$(KAFKA_ADVERTISED_HOST_NAME):9555
      KAFKA_LISTENERS: INSIDE://:9455,OUTSIDE://:9555
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:SSL,OUTSIDE:SSL
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_SSL_ENDPOINT_IDENTIFICATION_ALGORITHM: ""
      KAFKA_ADVERTISED_PROTOCOL_NAME: OUTSIDE
      KAFKA_ADVERTISED_PORT: 9555
      KAFKA_PROTOCOL_NAME: INSIDE
      KAFKA_PORT: 9455
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      apinet:
        aliases:
          - kafka
  cfssl:
    image: localhost:5000/savior-cfssl
    build: "./control/savior-ca"
    ports:
      - "3030:3030"
    networks:
      apinet:
        aliases:
          - cfssl
  api:
    image: localhost:5000/savior-api
    build: "./control/api_server"
    ports:
      - "17141:17141"
      - "17504:17504"
    environment:
      CFSSL_SHARED_SECRET: "de1069ab43f7f385d9a31b76af27e7620e9aa2ad5dccd264367422a452aba67f"
      SWARM_HOST: ${SWARM_HOSTNAME}
    depends_on:
      - kafka
      - cfssl
      - api_server_postgres
    networks:
      apinet:
        aliases:
          - api
  api_server_postgres:
    image: postgres:9.3
    volumes:
      - db-data:/var/lib/postgresql/data/pgdata
    environment:
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_USER: "postgres"
      PGDATA: "/var/lib/postgresql/data/pgdata"
      POSTGRES_DB: "api_server_postgres"
    deploy:
      placement:
        constraints: [node.role == manager]
    networks:
      apinet:
        aliases:
          - api_server_postgres
          - postgres
  api_ntpd:
    image: localhost:5000/api-ntpd
    build: "./control/savior-ntpd"
    ports:
      - "123:123/udp"
    networks:
      apinet:
        aliases:
          - ntp-server
volumes:
  db-data:
networks:
  apinet:
    external: true