version: '3.2'
services:
  registry:
    restart: always
    image: registry:2
    ports:
      - target: 5000
        published: 5000
        protocol: tcp
    networks:
      apinet:
        aliases:
          - registry
networks:
  apinet:
    external: true