version: '3.2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    build:
      context: "./control/logging"
      dockerfile: Dockerfile
    ports:
      - target: 9555
        published: 9555
        protocol: tcp
        mode: host
    environment:
      CFSSL_SHARED_SECRET: "de1069ab43f7f385d9a31b76af27e7620e9aa2ad5dccd264367422a452aba67f"
      HOSTNAME_COMMAND: "docker info | grep ^Name: | cut -d' ' -f 2"      
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:SSL,OUTSIDE:SSL
      KAFKA_ADVERTISED_PROTOCOL_NAME: OUTSIDE
      KAFKA_ADVERTISED_PORT: 9555
      KAFKA_PROTOCOL_NAME: INSIDE
      KAFKA_PORT: 9455
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  cfssl:
    build: "./control/savior-ca"
    ports:
      - "3030:3030"
  api:
    build: "./control/api_server"
    ports:
      - "17141:17141"
      - "17504:17504"
    environment:
      CFSSL_SHARED_SECRET: "de1069ab43f7f385d9a31b76af27e7620e9aa2ad5dccd264367422a452aba67f"
    depends_on:
      - kafka
      - cfssl
      - api_server_postgres
    links:
      - "kafka:kafka"
      - "cfssl:cfssl"
  dropper_callback:
    build: "./external/dropper_callback"
    ports:
      - "8080:8080"
    # hostname: dropper1
    # domainname: evil.io
  target_1:
    build: "./targets/demo-target"
    depends_on:
      - kafka
      - api
    stdin_open: true
    tty: true
  api_server_postgres:
    image: postgres:9.3
    volumes:
      - ./pgdata:/var/lib/postgresql/data/pgdata
    environment:
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_USER: "postgres"
      PGDATA: "/var/lib/postgresql/data/pgdata"
      POSTGRES_DB: "api_server_postgres"
  nfs_sensor:
    build: "./targets/nfs-sensor-target"
    environment:
      CFSSL_SHARED_SECRET: "de1069ab43f7f385d9a31b76af27e7620e9aa2ad5dccd264367422a452aba67f"
      NFS_SENSOR_SNIFF_INTERFACE: "vif1.0"
      NFS_SENSOR_STANDALONE: ""
    #networks:
    #  external:
    #    name: host
    #  - savior_default
    network_mode: host
    tty: true
#networks:
#  hostnet:
#    external:
#      name: host
#  default: