version: '2'
services:
  kafka:
    image: spotify/kafka
    ports:
      - "2181:2181"
      - "9092:9092"
    environment:
      ADVERTISED_HOST: kafka
      ADVERTISED_PORT: "9092"
  cfssl:
    build: "./control/savior-ca"
    ports:
      - "3030:3030"
  api:
    build: "./control/api_server"
    ports:
      - "17504:17504"
    depends_on:
      - kafka
      - cfssl
    links:
      - "kafka:kafka"
      - "cfssl:cfssl"
  sensor_1:
    build: "./sensors/dummy"
    ports:
      - "11000:11000"
      - "5002:5002"
    depends_on:
      - kafka
      - api
    command: python lsof_sensor.py --public-key-path ./cert/rsa_key.pub --private-key-path ./cert/rsa_key --api-host api --sensor-port 11000 --delay-start 10
  sensor_2:
    build: "./sensors/dummy"
    ports:
      - "11001:11001"
    depends_on:
      - kafka
      - api
    command: python lsof_sensor.py --public-key-path ./cert/rsa_key.pub --private-key-path ./cert/rsa_key --api-host api --sensor-port 11001 --delay-start 10