= Sensing API NTPD Server
Patrick Dwyer <patrick.dwyer@twosixlabs.com>
v0.1, 2018-05-22
:version: 0.1.0

ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]


An NTP server for the Sensing Infrastructure and the SAVIOR environment.

WARNING: This NTPD server is not currently configured for any API services, nor deployed in Dev, Test, or Production.

== Deployment

This NTP Service container is designed to run, without privileges, in a normal
Docker environment, or in a Swarm environment. Running in a normal Docker environment requires
specifically exposing the NTP UDP ports, see <<Testing>>.


== Configuration

The NTPD server is configured with the link:chrony-config.conf[chrony-config.conf file].
By default we're using the 4 primary servers of the North America NTP pool, but this can be
reconfigured to use APL internal NTP servers, or Amazon NTP servers in AWS.

Allowed Clients::

* `10.0.0.0/8`
* `172.16.0.0/12`
* `192.168.0.0/16`
* `127.0.0.0/8`
* `2001:aaaa:bbbb:cccc::/64`

Stratum::

level 5

Upstream Servers::

* 0.north-america.pool.ntp.org
* 1.north-america.pool.ntp.org
* 2.north-america.pool.ntp.org
* 3.north-america.pool.ntp.org

== Testing

For testing purposes, you can run the Chrony NTPD server independently.

.Build NTPD Server
[source,bash]
----
docker build -t twosixlabs/chrony-ntpd:latest .
----

.Running NTPD Server
[source,bash]
----
docker run --rm -d --name chrony-ntpd -p 123:123/udp twosixlabs/chrony-ntpd:latest
----

.Query NTPD Server
[source,bash]
----
ntpdate -q localhost
----

If an NTPD host isn't running, bound to `localhost`, you might see results like:

[source,bash]
----
ntpdate -q localhost
server ::1, stratum 0, offset 0.000000, delay 0.00000
server 127.0.0.1, stratum 0, offset 0.000000, delay 0.00000
23 May 08:32:43 ntpdate[20261]: no server suitable for synchronization found
----

If the NTPD server is running, results may look more like:

[source,bash]
----
ntpdate -q localhost
server ::1, stratum 0, offset 0.000000, delay 0.00000
server 127.0.0.1, stratum 5, offset -7.678735, delay 0.02660
23 May 08:39:46 ntpdate[20714]: step time server 127.0.0.1 offset -7.678735 sec
----


